@echo off
REM ****************************************************************************
REM Vivado (TM) v2021.1 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Thu Feb 20 19:40:56 -0500 2025
REM SW Build 3247384 on Thu Jun 10 19:36:33 MDT 2021
REM
REM IP Build 3246043 on Fri Jun 11 00:30:35 MDT 2021
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
REM simulate design
echo "xsim mac_tb_time_synth -key {Post-Synthesis:sim_1:Timing:mac_tb} -tclbatch mac_tb.tcl -view C:/work/research/Accelerator/VIT/vit_accel/waveform_configs/PE_wrapper_tb_behav.wcfg -log simulate.log"
call xsim  mac_tb_time_synth -key {Post-Synthesis:sim_1:Timing:mac_tb} -tclbatch mac_tb.tcl -view C:/work/research/Accelerator/VIT/vit_accel/waveform_configs/PE_wrapper_tb_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
