######################################################################
##
## Filename: mac_tb_wave.do
## Created on: Fri Feb 21 14:30:43 2025
##
##  Auto generated by Vivado for Behavioral Simulation
##
##  You may want to edit this file to control the simulation
##
######################################################################
add wave *
add wave /glbl/GSR
