######################################################################
##
## Filename: mac_tb.do
## Created on: Fri Feb 21 14:30:43 2025
##
##  Auto generated by Vivado for Behavioral Simulation
##
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##  You may want to add additional commands to control the simulation
##  in the user specific do file (<module>.udo) which is automatically
##  generated in the simulation directory and will not be removed on
##  subsequent simulation flow runs from Vivado.
##  ---------------------DO NOT EDIT THIS FILE-------------------------
##
######################################################################
#

#
# Create work library
#
vlib work
vlib msim/xil_defaultlib

#
# Map libraries
#
vmap xil_defaultlib msim/xil_defaultlib

#
# Design sources
#
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/mac.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/processing_element.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/A_buff.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/B_buff.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/O_buff.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/adder.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/adder_col.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/config_regs.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/noc_v2.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/pe_array_v2.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/pe_row.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/sp_ram.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/PE_wrapper.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/noc.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/pe_array.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new/mac_v2.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/A_buff_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/PE_wrapper_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/noc_v2_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/pe_row_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/pe_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/pe_array_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/mac_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/adder_col_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new
vlog  -incr  -work xil_defaultlib  "C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sim_2/imports/new/pe_array_v2_tb.v" +incdir+C:/work/research/Accelerator/VIT/vit_accel/vit_accel.srcs/sources_1/new

#
# Add global set/reset
#
vlog -work xil_defaultlib "C:/Xilinx/Vivado/2024.2/data/verilog/src/glbl.v"

#
# Call vsim to invoke simulator
#
vsim -voptargs="+acc" -t 1ps -L unisims_ver -L unimacro_ver -L secureip -L xil_defaultlib -lib xil_defaultlib xil_defaultlib.mac_tb xil_defaultlib.glbl

#
# Source wave do file
#
do {mac_tb_wave.do}

#
# Set the window types
#
view wave
view structure
view signals

#
# Source user do file (UDO)
#
do {mac_tb.udo}

#
# Run simulation for this time
#
run 1000ns


#
# End
#
