# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_resetJobStats
    rt::HARTNDb_resetSystemStats
    rt::HARTNDb_startSystemStats
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "E:/Miki/JHU/research/Accelerator_2025/vit_accel/.Xil/Vivado-24764-DESKTOP-PQV8974/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file delete -force $::env(RT_TMP)
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7a200tfbg484-1
    source $::env(HRT_TCL_PATH)/rtSynthParallelPrep.tcl
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    set rt::useElabCache false
    if {$rt::useElabCache == false} {
      rt::read_verilog -include E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new {
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/mac.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/processing_element.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/A_buff.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/B_buff.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/O_buff.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/adder.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/adder_col.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/config_regs.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/noc_v2.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/pe_array_v2.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/pe_row.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/sp_ram.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/PE_wrapper.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/mult_test.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/mac_temporal.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/pe_v2.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/mac_temporal_asic.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/workload_controller.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/controller.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/subtractor.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/mac_unit.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/processing_element_v2.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/pe_row_v2.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/adder_v2.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/pe_array_v3.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/attention_block.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/pe_wrapper_v2.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/pe_output_buffer.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/attn_multiplier.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/attn_pe_grid.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/attn_pe.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/attn_pe_row.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/qkv_block.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/ff_block.v
      E:/Miki/JHU/research/Accelerator_2025/vit_accel/vit_accel.srcs/sources_1/new/top.v
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification false
    set rt::top top
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly true
    rt::set_parameter elaborateRtl true
    rt::set_parameter eliminateRedundantBitOperator false
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow true
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter merge_flipflops true
    rt::set_parameter srlDepthThreshold 3
    rt::set_parameter rstSrlDepthThreshold 4
# MODE: 
    rt::set_parameter webTalkPath {}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "E:/Miki/JHU/research/Accelerator_2025/vit_accel/.Xil/Vivado-24764-DESKTOP-PQV8974/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_rtlelab -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
uplevel #0 { 
   $rt::db resetHdlParse
   set hsKey [rt::get_parameter helper_shm_key] 
   if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
      $rt::db killSynthHelper $hsKey
   } 
   source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
   return -code "error" $rt::result
 }
}
